apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd   # must match labels in Deployment
  ports:
    - protocol: TCP
      port: 80        # External Service port
      targetPort: 80  # Container port
  type: LoadBalancer
